"""empty message

Revision ID: 7a7da1e1bd2b
Revises: de278f6c4402
Create Date: 2019-12-05 18:01:27.916160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7da1e1bd2b'
down_revision = 'de278f6c4402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_username', table_name='items')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('username', sa.VARCHAR(length=64), nullable=False))
    op.create_foreign_key(None, 'items', 'user', ['username'], ['username'])
    op.create_index('ix_items_username', 'items', ['username'], unique=False)
    # ### end Alembic commands ###
