"""empty message

Revision ID: 8ae0f996acf6
Revises: c240a26b0d95
Create Date: 2020-01-26 20:52:25.936844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae0f996acf6'
down_revision = 'c240a26b0d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'id')
    op.add_column('sales', sa.Column('packaging', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'packaging')
    op.add_column('items', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
