"""Preparing for testing.

Revision ID: 96878b29ffa2
Revises: 84a2cd9e4b40
Create Date: 2019-11-16 12:46:54.622702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96878b29ffa2'
down_revision = '84a2cd9e4b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('itemName', sa.String(length=255), nullable=False))
    op.alter_column('items', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('items', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_items_itemName'), 'items', ['itemName'], unique=True)
    op.drop_index('ix_items_item', table_name='items')
    op.create_foreign_key(None, 'items', 'user', ['username'], ['username'])
    op.drop_column('items', 'item')
    op.drop_column('items', 'id')
    op.add_column('sales', sa.Column('itemName', sa.String(length=255), nullable=False))
    op.add_column('sales', sa.Column('profit', sa.Float(precision=2), nullable=False))
    op.alter_column('sales', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('sales', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('sales', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'shipping',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('sales', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_index(op.f('ix_sales_itemName'), 'sales', ['itemName'], unique=False)
    op.drop_index('ix_sales_item', table_name='sales')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'items', ['itemName'], ['itemName'])
    op.drop_column('sales', 'item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('item', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'items', ['item'], ['item'])
    op.create_index('ix_sales_item', 'sales', ['item'], unique=False)
    op.drop_index(op.f('ix_sales_itemName'), table_name='sales')
    op.alter_column('sales', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('sales', 'shipping',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('sales', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('sales', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('sales', 'profit')
    op.drop_column('sales', 'itemName')
    op.add_column('items', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('items', sa.Column('item', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_index('ix_items_item', 'items', ['item'], unique=1)
    op.drop_index(op.f('ix_items_itemName'), table_name='items')
    op.alter_column('items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('items', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('items', 'itemName')
    # ### end Alembic commands ###
