"""empty message

Revision ID: b0ee99709c72
Revises: 7a7da1e1bd2b
Create Date: 2019-12-05 18:44:33.532684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ee99709c72'
down_revision = '7a7da1e1bd2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('itemName', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shipping', sa.Float(precision=2), nullable=False),
    sa.Column('profit', sa.Float(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['itemName'], ['items.itemName'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_index(op.f('ix_sales_itemName'), 'sales', ['itemName'], unique=False)
    op.create_index(op.f('ix_sales_username'), 'sales', ['username'], unique=False)
    op.alter_column('items', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('ix_items_username'), 'items', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_username'), table_name='items')
    op.alter_column('items', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index(op.f('ix_sales_username'), table_name='sales')
    op.drop_index(op.f('ix_sales_itemName'), table_name='sales')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
