"""empty message

Revision ID: b74213cb0af6
Revises: 5b057b320aa6
Create Date: 2019-12-04 14:06:57.653459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74213cb0af6'
down_revision = '5b057b320aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'id')
    # ### end Alembic commands ###
