"""empty message

Revision ID: c240a26b0d95
Revises: 7e0deba27edc
Create Date: 2020-01-26 20:50:17.426099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c240a26b0d95'
down_revision = '7e0deba27edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'id')
    op.add_column('sales', sa.Column('packaging', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'packaging')
    op.add_column('items', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
